
name: Telegram Upload
on:
  workflow_call:
    inputs:
      from_ci:
        type: boolean
        required: false
        default: true

  workflow_dispatch:

jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

  
      - name: Report to Telegram
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
        if: env.TG_TOKEN != null
        run: |
          cd build || { echo "build folder not found"; exit 1; }

          TG_CHAT="-1002089161312"
          NL=$'\n'
          APKS=""
          MODULES=""
          for OUTPUT in *; do
            DL_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}/${OUTPUT}"
            if [[ $OUTPUT = *.apk ]]; then
              APKS+="${NL}📦[${OUTPUT}](${DL_URL})"
            elif [[ $OUTPUT = *.zip ]]; then
              MODULES+="${NL}📦[${OUTPUT}](${DL_URL})"
            fi
          done
          MODULES=${MODULES#"$NL"}
          APKS=${APKS#"$NL"}

          BODY="$(sed 's/^\* \*\*/↪ \*\*/g; s/^\* `/↪ \*\*/g; s/`/\*/g; s/^\* /\↪/g; s/\*\*/\*/g; s/###//g; s/^- /↪ /g; /^==/d;' ../build.md)"
          MSG="*📰 New build!*

          ${BODY}
         
          *▼ Download:*
          "
          echo "'$MSG'"
          MSG=${MSG:0:9450}
          POST="https://api.telegram.org/bot${TG_TOKEN}/sendMessage"
          RESPONSE=$(curl -s -X POST --data-urlencode "parse_mode=Markdown" --data-urlencode "disable_web_page_preview=true" --data-urlencode "text=${MSG}" --data-urlencode "chat_id=${TG_CHAT}" "$POST")
          MESSAGE_ID=$(echo $RESPONSE | jq -r '.result.message_id')

          PIN_POST="https://api.telegram.org/bot${TG_TOKEN}/pinChatMessage"
          curl -s -X POST --data-urlencode "chat_id=${TG_CHAT}" --data-urlencode "message_id=${MESSAGE_ID}" "$PIN_POST"
          
      - name: Prepare Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Ganti dengan versi Python yang dibutuhkan

      - name: Install pyrogram and tgcrypto
        run: |
          pip install -U pyrogram tgcrypto

      - name: Run upload.py
        env:
          API_ID: ${{ secrets.TG_API_ID }}
          API_HASH: ${{ secrets.TG_API_HASH }}
          BOT_TOKEN: ${{ secrets.TG_TOKEN }}
        run: curl -o upload.py https://raw.githubusercontent.com/kotakbiasa/TelegramZipUploader/main/upload.py && python upload.py --dir build --api_id $API_ID --api_hash $API_HASH --bot_token $BOT_TOKEN

      - uses: actions/upload-artifact@v3.1.2
        with:
          name: logs
          path: logs
          if-no-files-found: ignore
